language: python
python:
    - 2.7

before_script:
    - sudo mkdir -p /etc/ppp/
    - sudo touch /etc/ppp/chap-secrets

script: 
    - sudo python server.py start > /dev/stdout &
    - sleep 30
    - curl -v http://127.0.0.1:8000/ 
    - curl -v http://127.0.0.1:8000/create 
    - curl -v http://127.0.0.1:8000/users
    - curl -v --data "_username=test&_password=test&_server=*&_ip=*" http://127.0.0.1:8000/add-user 
    - curl -v http://127.0.0.1:8000/users
