language: python
python:
    - 2.7

before_script:
    - sudo su
    - echo -e "test\t*\t12345\t*" >> /etc/ppp/chap-secrets

script: 
    - sudo python server.py start > /dev/stdout &
    - curl http://0.0.0.0:8000/ 
    - curl http://0.0.0.0:8000/create
    - curl http://0.0.0.0:8000/users

after_script:
    - rm /etc/ppp/chap-secrets